In [1]:
import pandas as pd
from src.utils.config import RAW_DATA_DIR 
from src.data.load_data import load_data , load_detail_data

In [3]:
main_df = load_data(RAW_DATA_DIR) # main dataset loading
dis_df , pre_df , home_df= load_detail_data(RAW_DATA_DIR) # additional dataset loading

data loaded successfully.

In [4]:
main_df.head()

            Disease   Symptom_1  ... Symptom_16 Symptom_17
0  Fungal infection     itching  ...        NaN        NaN
1  Fungal infection   skin_rash  ...        NaN        NaN
2  Fungal infection     itching  ...        NaN        NaN
3  Fungal infection     itching  ...        NaN        NaN
4  Fungal infection     itching  ...        NaN        NaN

[5 rows x 18 columns]

In [5]:
main_df.shape

(4920, 18)

In [6]:
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Disease     4920 non-null   object
 1   Symptom_1   4920 non-null   object
 2   Symptom_2   4920 non-null   object
 3   Symptom_3   4920 non-null   object
 4   Symptom_4   4572 non-null   object
 5   Symptom_5   3714 non-null   object
 6   Symptom_6   2934 non-null   object
 7   Symptom_7   2268 non-null   object
 8   Symptom_8   1944 non-null   object
 9   Symptom_9   1692 non-null   object
 10  Symptom_10  1512 non-null   object
 11  Symptom_11  1194 non-null   object
 12  Symptom_12  744 non-null    object
 13  Symptom_13  504 non-null    object
 14  Symptom_14  306 non-null    object
 15  Symptom_15  240 non-null    object
 16  Symptom_16  192 non-null    object
 17  Symptom_17  72 non-null     object
dtypes: object(18)
memory usage: 692.0+ KB

In [7]:
main_df["Disease"].value_counts()

Disease
Fungal infection                           120
Allergy                                    120
GERD                                       120
Chronic cholestasis                        120
Drug Reaction                              120
Peptic ulcer diseae                        120
AIDS                                       120
Diabetes                                   120
Gastroenteritis                            120
Bronchial Asthma                           120
Hypertension                               120
Migraine                                   120
Cervical spondylosis                       120
Paralysis (brain hemorrhage)               120
Jaundice                                   120
Malaria                                    120
Chicken pox                                120
Dengue                                     120
Typhoid                                    120
hepatitis A                                120
Hepatitis B                                120
Hepatitis C                                120
Hepatitis D                                120
Hepatitis E                                120
Alcoholic hepatitis                        120
Tuberculosis                               120
Common Cold                                120
Pneumonia                                  120
Dimorphic hemmorhoids(piles)               120
Heart attack                               120
Varicose veins                             120
Hypothyroidism                             120
Hyperthyroidism                            120
Hypoglycemia                               120
Osteoarthristis                            120
Arthritis                                  120
(vertigo) Paroymsal  Positional Vertigo    120
Acne                                       120
Urinary tract infection                    120
Psoriasis                                  120
Impetigo                                   120
Name: count, dtype: int64

In [13]:
from src.data.load_data import load_data
df = load_data(RAW_DATA_DIR)

data loaded successfully.

In [14]:
from src.data.clean_data import data_clean
df = data_clean(df)

Data cleaning is complete successfully

In [15]:
from src.data.split_data import features_split
X , y = features_split(df)

features split is complete successfully.

In [16]:
from src.features.train_test_split import train_test_split_data
X_train , X_test , y_train, y_test = train_test_split_data(X, y , train_size=0.8)

In [17]:
from src.features.encoding import symptoms_extract , y_scaler , x_encoding , x_test_encoding , y_test_scaling
symptoms = symptoms_extract(X)
X_train  , mlb= x_encoding(X_train)
encoder ,y_train = y_scaler(y_train)
X_test = x_test_encoding(X_test , mlb)
y_test = y_test_scaling(y_test , encoder)

X encoding is complete sucessfully.
Y feature encoding complete successfully.
X test encoding is complete sucessfully.
Y test encoding complete successfully.

In [18]:
from src.tuning.model_tuning import model_selection
best_model  , model , model_scores_dict = model_selection(X_train , y_train)

logistic regression: mean=100.00, std=0.000
Decision tree : mean=100.00, std=0.000
Random Forest: mean=100.00, std=0.000

In [19]:
from src.tuning.hyperparameter_tuning import tune_logistic_regression , tune_random_forest , best_hyperparameters
lr_model, lr_score, lr_params= tune_logistic_regression(X_train , y_train)
rf_model, rf_score, rf_params = tune_random_forest(X_train , y_train)
model = best_hyperparameters(lr_model, lr_score, rf_model, rf_score)

Best Model: Random Forest with score 1.0

In [20]:
print("LR:", lr_score, lr_params)
print("RF:", rf_score, rf_params)

LR: 1.0 {'solver': 'lbfgs', 'max_iter': 500, 'C': 0.01}
RF: 1.0 {'n_estimators': 100, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'max_depth': None}

In [21]:
from src.prediction.processing_input import transform_input ,  input_sysptoms
from src.prediction.prediction import home_remedies , predicted_disease

selected_symptoms = ['chest pain','back pain']
input_data = input_sysptoms(selected_symptoms)

input_encoded = transform_input(input_data , mlb)

pred = predicted_disease(input_encoded , model , encoder)
remidies , s_level , redation_ad = home_remedies(home_red , pred)

IndexError: index 0 is out of bounds for axis 0 with size 0

In [ ]:
home_red.shape

(41, 6)

In [ ]:
df.

In [22]:
home_red

,disease_name,home_remedy_1,home_remedy_2,home_remedy_3,severity_level,reaction_advice
0,Drug Reaction,Stop suspected drug (if safe),Cold compress for rash,Hydration,Level 4 - Serious,See doctor immediately; emergency if breathing...
1,Malaria,Stay hydrated,Rest,Light nutritious diet,Level 4 - Serious,Immediate medical diagnosis and antimalarial t...
2,Allergy,Avoid trigger,Steam inhalation,Antihistamine (doctor advised),Level 2 - Mild,Seek doctor if swelling or breathing difficulty
3,Hypothyroidism,Iodine-rich diet,Regular exercise,Stress management,Level 3 - Moderate,Consult endocrinologist; long-term medication ...
4,Psoriasis,Moisturize skin,Oatmeal bath,Aloe vera gel,Level 2 - Mild,See dermatologist if severe flare
5,GERD,Avoid spicy food,Eat small meals,Elevate head while sleeping,Level 2 - Mild,Doctor visit if persistent
6,Chronic cholestasis,Low-fat diet,Hydration,Avoid alcohol,Level 4 - Serious,Urgent liver specialist consultation
7,hepatitis A,Rest,Hydration,Avoid fatty food,Level 3 - Moderate,Medical supervision required
8,Osteoarthristis,Hot compress,Light exercise,Turmeric milk,Level 2 - Mild,Orthopedic consult if pain worsens
9,(vertigo) Paroymsal Positional Vertigo,Epley maneuver,Avoid sudden head movement,Hydration,Level 3 - Moderate,Doctor visit if frequent
10,Hypoglycemia,Consume sugar,Fruit juice,Glucose tablets,Level 4 - Serious,Immediate correction; emergency if unconscious
11,Acne,Wash face regularly,Aloe vera,Avoid oily food,Level 1 - Very Mild,Dermatologist if severe
12,Diabetes,Low sugar diet,Regular exercise,Monitor glucose,Level 4 - Serious,Regular medical management mandatory
13,Impetigo,Clean affected area,Apply prescribed ointment,Avoid scratching,Level 3 - Moderate,Doctor visit required
14,Hypertension,Low salt diet,Exercise,Stress control,Level 4 - Serious,Regular monitoring; emergency if very high BP
15,Peptic ulcer disease,Avoid spicy food,Eat small meals,Reduce stress,Level 3 - Moderate,Doctor evaluation needed
16,Dimorphic hemorrhoids(piles),High fiber diet,Warm sitz bath,Hydration,Level 2 - Mild,Doctor if bleeding severe
17,Common Cold,Steam inhalation,Warm fluids,Rest,Level 1 - Very Mild,Self care; doctor if persists >5 days
18,Chicken pox,Calamine lotion,Oatmeal bath,Rest,Level 3 - Moderate,Doctor supervision required
19,Cervical spondylosis,Neck exercises,Hot compress,Correct posture,Level 2 - Mild,Physiotherapy consult
20,Hyperthyroidism,Avoid excess iodine,Stress control,Regular monitoring,Level 4 - Serious,Endocrinologist consultation
21,Urinary tract infection,Drink water,Cranberry juice,Maintain hygiene,Level 3 - Moderate,Doctor for antibiotics
22,Varicose veins,Leg elevation,Compression stockings,Avoid prolonged standing,Level 2 - Mild,Doctor if pain severe
23,AIDS,Nutritious diet,Infection prevention,Mental health support,Level 5 - Critical,Strict antiretroviral therapy required
24,Paralysis (brain hemorrhage),None (Emergency),Keep patient stable,Do not move head,Level 5 - Critical,Call emergency services immediately
25,Typhoid,Hydration,Soft diet,Rest,Level 4 - Serious,Immediate antibiotic treatment
26,Hepatitis B,Avoid alcohol,Healthy diet,Rest,Level 4 - Serious,Liver specialist consultation
27,Fungal infection,Keep area dry,Antifungal cream,Loose clothing,Level 2 - Mild,Doctor if persistent
28,Hepatitis C,Avoid alcohol,Healthy diet,Rest,Level 4 - Serious,Specialist treatment required
29,Migraine,Dark quiet room,Cold compress,Hydration,Level 3 - Moderate,Doctor if frequent/severe
30,Bronchial Asthma,Steam inhalation,Avoid triggers,Use inhaler (prescribed),Level 4 - Serious,Emergency if breathing difficulty
31,Alcoholic hepatitis,Stop alcohol,Healthy diet,Hydration,Level 5 - Critical,Immediate medical care required
32,Jaundice,Hydration,Sugarcane juice,Rest,Level 3 - Moderate,Doctor supervision required
33,Hepatitis E,Rest,Hydration,Avoid fatty food,Level 3 - Moderate,Medical monitoring required
34,Dengue,Hydration,Papaya leaf extract (supportive),Rest,Level 4 - Serious,Immediate platelet monitoring
35,Hepatitis D,Avoid alcohol,Healthy diet,Rest,Level 4 - Serious,Specialist treatment needed
36,Heart attack,None (Emergency),Aspirin (if advised),Call emergency,Level 5 - Critical,Immediate hospital care required
37,Pneumonia,Steam inhalation,Rest,Hydration,Level 4 - Serious,Doctor immediately; antibiotics required
38,Arthritis,Warm compress,Exercise,Anti-inflammatory diet,Level 3 - Moderate,Rheumatologist consult
39,Gastroenteritis,ORS,Hydration,Light diet,Level 3 - Moderate,Doctor if dehydration severe
40,Tuberculosis,Nutritious diet,Isolation,Rest,Level 5 - Critical,Strict anti-TB treatment mandatory

In [ ]:
home_red.iloc[40]

disease_name                            Drug Reaction
home_remedy_1                         Nutritious diet
home_remedy_2                               Isolation
home_remedy_3                                    Rest
severity_level                     Level 5 - Critical
reaction_advice    Strict anti-TB treatment mandatory
Name: 40, dtype: object

In [ ]:
home_red[home_red["disease_name"] == "Drug Reaction"]

,disease_name,home_remedy_1,home_remedy_2,home_remedy_3,severity_level,reaction_advice
0,Drug Reaction,Stop suspected drug (if safe),Cold compress for rash,Hydration,Level 4 - Serious,See doctor immediately; emergency if breathing...
1,Drug Reaction,Stay hydrated,Rest,Light nutritious diet,Level 4 - Serious,Immediate medical diagnosis and antimalarial t...
2,Drug Reaction,Avoid trigger,Steam inhalation,Antihistamine (doctor advised),Level 2 - Mild,Seek doctor if swelling or breathing difficulty
3,Drug Reaction,Iodine-rich diet,Regular exercise,Stress management,Level 3 - Moderate,Consult endocrinologist; long-term medication ...
4,Drug Reaction,Moisturize skin,Oatmeal bath,Aloe vera gel,Level 2 - Mild,See dermatologist if severe flare
5,Drug Reaction,Avoid spicy food,Eat small meals,Elevate head while sleeping,Level 2 - Mild,Doctor visit if persistent
6,Drug Reaction,Low-fat diet,Hydration,Avoid alcohol,Level 4 - Serious,Urgent liver specialist consultation
7,Drug Reaction,Rest,Hydration,Avoid fatty food,Level 3 - Moderate,Medical supervision required
8,Drug Reaction,Hot compress,Light exercise,Turmeric milk,Level 2 - Mild,Orthopedic consult if pain worsens
9,Drug Reaction,Epley maneuver,Avoid sudden head movement,Hydration,Level 3 - Moderate,Doctor visit if frequent
10,Drug Reaction,Consume sugar,Fruit juice,Glucose tablets,Level 4 - Serious,Immediate correction; emergency if unconscious
11,Drug Reaction,Wash face regularly,Aloe vera,Avoid oily food,Level 1 - Very Mild,Dermatologist if severe
12,Drug Reaction,Low sugar diet,Regular exercise,Monitor glucose,Level 4 - Serious,Regular medical management mandatory
13,Drug Reaction,Clean affected area,Apply prescribed ointment,Avoid scratching,Level 3 - Moderate,Doctor visit required
14,Drug Reaction,Low salt diet,Exercise,Stress control,Level 4 - Serious,Regular monitoring; emergency if very high BP
15,Drug Reaction,Avoid spicy food,Eat small meals,Reduce stress,Level 3 - Moderate,Doctor evaluation needed
16,Drug Reaction,High fiber diet,Warm sitz bath,Hydration,Level 2 - Mild,Doctor if bleeding severe
17,Drug Reaction,Steam inhalation,Warm fluids,Rest,Level 1 - Very Mild,Self care; doctor if persists >5 days
18,Drug Reaction,Calamine lotion,Oatmeal bath,Rest,Level 3 - Moderate,Doctor supervision required
19,Drug Reaction,Neck exercises,Hot compress,Correct posture,Level 2 - Mild,Physiotherapy consult
20,Drug Reaction,Avoid excess iodine,Stress control,Regular monitoring,Level 4 - Serious,Endocrinologist consultation
21,Drug Reaction,Drink water,Cranberry juice,Maintain hygiene,Level 3 - Moderate,Doctor for antibiotics
22,Drug Reaction,Leg elevation,Compression stockings,Avoid prolonged standing,Level 2 - Mild,Doctor if pain severe
23,Drug Reaction,Nutritious diet,Infection prevention,Mental health support,Level 5 - Critical,Strict antiretroviral therapy required
24,Drug Reaction,None (Emergency),Keep patient stable,Do not move head,Level 5 - Critical,Call emergency services immediately
25,Drug Reaction,Hydration,Soft diet,Rest,Level 4 - Serious,Immediate antibiotic treatment
26,Drug Reaction,Avoid alcohol,Healthy diet,Rest,Level 4 - Serious,Liver specialist consultation
27,Drug Reaction,Keep area dry,Antifungal cream,Loose clothing,Level 2 - Mild,Doctor if persistent
28,Drug Reaction,Avoid alcohol,Healthy diet,Rest,Level 4 - Serious,Specialist treatment required
29,Drug Reaction,Dark quiet room,Cold compress,Hydration,Level 3 - Moderate,Doctor if frequent/severe
30,Drug Reaction,Steam inhalation,Avoid triggers,Use inhaler (prescribed),Level 4 - Serious,Emergency if breathing difficulty
31,Drug Reaction,Stop alcohol,Healthy diet,Hydration,Level 5 - Critical,Immediate medical care required
32,Drug Reaction,Hydration,Sugarcane juice,Rest,Level 3 - Moderate,Doctor supervision required
33,Drug Reaction,Rest,Hydration,Avoid fatty food,Level 3 - Moderate,Medical monitoring required
34,Drug Reaction,Hydration,Papaya leaf extract (supportive),Rest,Level 4 - Serious,Immediate platelet monitoring
35,Drug Reaction,Avoid alcohol,Healthy diet,Rest,Level 4 - Serious,Specialist treatment needed
36,Drug Reaction,None (Emergency),Aspirin (if advised),Call emergency,Level 5 - Critical,Immediate hospital care required
37,Drug Reaction,Steam inhalation,Rest,Hydration,Level 4 - Serious,Doctor immediately; antibiotics required
38,Drug Reaction,Warm compress,Exercise,Anti-inflammatory diet,Level 3 - Moderate,Rheumatologist consult
39,Drug Reaction,ORS,Hydration,Light diet,Level 3 - Moderate,Doctor if dehydration severe
40,Drug Reaction,Nutritious diet,Isolation,Rest,Level 5 - Critical,Strict anti-TB treatment mandatory

In [ ]:




predicted_disease(input_encoded , model , encoder)
dict = top_3_predictions(input_encoded , model , encoder)
print("Top 3 Predicted Diseases and Probabilities:", dict)
for disease, prob in dict:
    print(f"{disease}: {prob*100:.2f}%")
dis = disease_description(full_data['description'] , "Heart attack")
pre_list = disease_precautions(full_data['precaution'] , "Heart attack")
remedies_list , s_level , reaction_advi = home_remedies(homecare_df= home_red , disease_name= "Heart attack")
print(pre_list)
print("-"*30)
for remedis in remedies_list:
    print(remedis)
print(s_level)
print("-"*30)
print(reaction_advi)

In [ ]:
x = home_red[home_red["disease_name"]== "Drug Reaction"]
y = x["reaction_advice"].values
print(y)

In [ ]:
dis

In [ ]:
pred = model.predict(input_encoded)[0]
decoded_pred = encoder.inverse_transform([pred])
print("Predicted Disease:", decoded_pred[0])
print("predicted probabilities:", )

In [ ]:

probs = model.predict_proba(input_encoded)

top3_indices = np.argsort(probs[0])[::-1][:3]

top3_probs = probs[0][top3_indices]

top3_diseases = model.classes_[top3_indices]

for disease, prob in zip(top3_diseases, top3_probs):
    disease_name = encoder.inverse_transform([disease])[0]
    print(f"{disease_name}: {prob*100:.2f}%")